version: "3"
services: 
    mysql-database:
        image: mysql:8.0.17
        container_name: proQrentGoldDatabase
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: proQrentGold
        ports:
           - "3308:3306"

    keycloak:
        image: jboss/keycloak
        container_name: "proQrentGoldKeycloak"
        ports: 
            - 8000:8080
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin



              
